{
 "title": "Node Details",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Node Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "count(kube_node_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Ready Nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\", status=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unschedulable Nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_spec_unschedulable{unschedulable=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes With Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (node) (kube_pod_info{node!=\"\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Node Selection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Node Overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m]) * 100) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) by (instance) / sum(node_memory_MemTotal_bytes) by (instance) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by (node) (kube_pod_info{node!=\"\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance) (node_filesystem_avail_bytes{fstype!=\"tmpfs\",mountpoint=\"/\"}) / sum by (instance) (node_filesystem_size_bytes{fstype!=\"tmpfs\",mountpoint=\"/\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage by Mode",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\",instance=~\"$instance\"}[5m])) by (mode) * 100 / scalar(count(node_cpu_seconds_total{mode=\"idle\",instance=~\"$instance\"}))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"} - node_memory_MemAvailable_bytes{instance=~\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$instance\"}",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{instance=~\"$instance\", fstype!=\"tmpfs\", mountpoint=\"/\"}",
     "legendFormat": "Free - {{mountpoint}}"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$instance\", fstype!=\"tmpfs\", mountpoint=\"/\"} - node_filesystem_free_bytes{instance=~\"$instance\", fstype!=\"tmpfs\", mountpoint=\"/\"}",
     "legendFormat": "Used - {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{instance=~\"$instance\"}[5m])) by (device)",
     "legendFormat": "Receive - {{device}}"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{instance=~\"$instance\"}[5m])) by (device)",
     "legendFormat": "Transmit - {{device}}"
    }
   ]
  }
 ]
}