apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
    component: sample-app
spec:
  selector:
    app: frontend
    component: sample-app
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 8080
    targetPort: 8080
    name: metrics
  type: ClusterIP