apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app: database
    component: sample-app
spec:
  selector:
    app: database
    component: sample-app
  ports:
  - port: 5000
    targetPort: 5000
    name: http
  type: ClusterIP